name: pisttopapp

services:
  messagebroker:
    image: apache/kafka:3.8.1
    environment:
      KAFKA_NODE_ID: 1 
      KAFKA_PROCESS_ROLES: broker,controller 
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093 
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://messagebroker:9092 
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER 
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT 
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093 
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1 
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1 
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0 
      KAFKA_NUM_PARTITIONS: 3 
    networks:
      - bridge_network
    ports:
      - 9092:9092

  vehicledb:
    image: postgres:17.2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: vehicles
    networks:
      - vehicle_network
   
  vehiclemanagement:
     build: ./vehicle_management/
     volumes:
       - type: bind
         source: ./vehicle_management/
         target: /app
     depends_on:
       - vehicledb
       - messagebroker
     networks:
       - vehicle_network
       - bridge_network
     ports:
       - 5000:5000
   
  customerdb:
     image: postgres:17.2
     environment:
       POSTGRES_USER: admin
       POSTGRES_PASSWORD: admin
       POSTGRES_DB: customers
     networks:
       - customer_network

  customermanagement:
    build: ./customer_management/
    volumes:
      - type: bind
        source: ./customer_management
        target: /app
    depends_on:
      - customerdb
      - messagebroker
    networks:
      - customer_network
      - bridge_network
    ports:
      - 5001:5000

  workshopeventhandler:
    build: ./workshop_event_handler/
    depends_on:
      - messagebroker
    volumes:
      - type: bind
        source: ./workshop_event_handler
        target: /app
      - type: volume
        source: workshopdb
        target: /app/db
    networks:
      - bridge_network

  workshopeventsourcingdb:
    image: mongodb/mongodb-community-server:7.0.8-ubi9
    networks:
      - workshop_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  workshopmanagement:
    build: ./workshop_management
    networks:
      - workshop_network
      - bridge_network
    volumes:
      - type: bind
        source: ./workshop_management
        target: /app
      - type: volume
        source: workshopdb
        target: /app/db
    depends_on:
      - messagebroker
      - workshopeventsourcingdb 
      - workshopeventhandler
    ports:
      - 5002:5000

networks:
  vehicle_network:
    driver: bridge
  customer_network:
    driver: bridge
  bridge_network:
    driver: bridge
  workshop_network:
    driver: bridge

volumes:
  workshopdb:
