name: vehicle_management

services:
  db:
    image: postgres:17.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: vehicles
  
  #  kafkaconnect:
  #    image: confluentinc/cp-kafka-connect:7.8.0
  #    environment:
  #      CONNECT_BOOTSTRAP_SERVERS: localhost:9092
  #      CONNECT_GROUP_ID: kafka-connect
  #      CONNECT_CONFIG_STORAGE_TOPIC: _connect-config
  #      CONNECT_OFFSET_STORAGE_TOPIC: _connect-offsets
  #      CONNECT_STATUS_STORAGE_TOPIC: _connect-state
  #      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
  #      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
  #      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
  #      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
  #      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
  #      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
  #      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
  #      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
  #      CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components,/data/connect-jars
  #    depends_on:
  #      - db
  #    network_mode: host
  #    command: 
  #      - bash
  #      - -c
  #      - |
  #        confluent-hub install debezium/debezium-connector-postgresql:latest --no-prompt
  #        confluent-hub install confluentinc/kafka-connect-jdbc:latest --no-prompt
  #        #
  #        /etc/confluent/docker/run &
  #        #
  #        sleep infinity
