name: customer_management

services:
  db:
    image: postgres:17.2
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: customers

  server:
    build: .
    depends_on:
      - db
    ports:
      - 5001:5000
    volumes:
      - type: bind
        source: .
        target: /app
